---

- name: get unifi bin zip
  become: true
  command: wget http://dl.ubnt.com/unifi/5.5.20/UniFi.unix.zip -O /usr/local/src/UniFi.unix.zip
  args: 
    chdir: /usr/local/src
    creates: /usr/local/src/UniFi.unix.zip
  tags:
    - unifi
    - unifi_wget

- name: unzip UniFi
  become: true
  command: unzip UniFi.unix.zip -d /opt
  args:
    chdir: /usr/local/src
    creates: /opt/UniFi
  tags:
    - unifi
    - unifi_unzip

- name: recursively chown /opt/UniFi
  become: true
  file: path=/opt/UniFi
        owner=unifi
        group=unifi
        state=directory
        recurse=yes
  tags:
    - unifi
    - unifi_chown

- name: install systemd startup file for unifi
  become: true
  copy: src=unifi.service
        dest=/usr/lib/systemd/system/
  notify: systemctl daemon-reload
  tags:
    - unifi
    - unifi_systemd

- name: systemctl enable unifi.service
  become: true
  service: name=unifi.service
           enabled=yes
           state=started
  tags:
    - unifi
    - unifi_systemd
